# Generated by Django 5.2.5 on 2025-11-10 08:45

import django.db.models.deletion
import django.db.models.manager
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(default='NA', max_length=500)),
                ('profile', models.ImageField(default='user/profile/user_default.jpg', upload_to='user/profile/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('place', models.CharField(max_length=255)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('general_label', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('vip_label', models.CharField(blank=True, max_length=50, null=True)),
                ('vip_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('vip_quantity', models.IntegerField(default=0)),
                ('economy_label', models.CharField(blank=True, max_length=50, null=True)),
                ('economy_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('economy_quantity', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.currency')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='EventAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('trailer', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=200)),
                ('cast', models.TextField(blank=True, default='')),
                ('language', models.CharField(max_length=100)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filmshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('theater_name', models.CharField(max_length=255)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('adult', models.DecimalField(decimal_places=1, max_digits=6)),
                ('child', models.DecimalField(decimal_places=1, max_digits=6)),
                ('street', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.currency')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmshow', to='db.film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmShowAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.filmshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('state_short', models.CharField(blank=True, max_length=500)),
                ('time_zone', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.country')),
            ],
        ),
        migrations.AddField(
            model_name='filmshow',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.state'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.state'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster_image', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('no_adult', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('no_child', models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True)),
                ('price_adult', models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True)),
                ('price_child', models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True)),
                ('economy_label', models.CharField(blank=True, max_length=50, null=True)),
                ('economy_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('economy_quantity', models.IntegerField(default=0)),
                ('general_label', models.CharField(blank=True, max_length=50, null=True)),
                ('general_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('general_quantity', models.IntegerField(default=0)),
                ('vip_label', models.CharField(blank=True, max_length=50, null=True)),
                ('vip_price', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('vip_quantity', models.IntegerField(default=0)),
                ('total_payment', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('theater_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=100)),
                ('payment_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0)),
                ('payment_date', models.DateTimeField()),
                ('attended', models.BooleanField(default=False)),
                ('attended_no', models.IntegerField(default=0)),
                ('attend_remarks', models.TextField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.country')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.event')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.film')),
                ('filmshow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.filmshow')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.state')),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.state')),
            ],
        ),
    ]
