# Generated by Django 5.2.5 on 2025-09-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='time_zone',
            new_name='state_time_zone',
        ),
    ]
