# Generated by Django 5.2.5 on 2026-03-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='economy_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='economy_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='economy_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='general_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='vip_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='vip_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='vip_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
