# Generated by Django 5.2.5 on 2026-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_event_bill_filmshow_bill_filmshow_economy_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='percent',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=8),
        ),
        migrations.AddField(
            model_name='filmshow',
            name='percent',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=8),
        ),
    ]
