# Generated by Django 5.2.5 on 2025-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_time_zone_state_state_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state_time_zone',
        ),
        migrations.AddField(
            model_name='state',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='economy_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
