# Generated by Django 5.2.5 on 2025-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_state_state_time_zone_state_time_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attended_no',
            field=models.IntegerField(default=0),
        ),
    ]
